version: 2.1

references:
  base_image: &base_image
    cimg/python:3.9.0

  repo_cache_key: &repo_cache_key
    repo-{{ .Branch }}-{{ .Revision }}-{{ .Environment.CACHE_KEY }}

  working_directory: &working_directory
    /home/circleci/project

  default_config: &default_config
    docker:
      - image: *base_image
    working_directory: *working_directory

  restore_repo: &restore_repo
    restore_cache:
      key: *repo_cache_key

  save_repo: &save_repo
    save_cache:
      key: *repo_cache_key
      paths:
        - /home/circleci/
        - /home/.pyenv

commands:
  restore:
    steps:
      - checkout
      - *restore_repo

jobs:
  install:
    <<: *default_config
    steps:
      - run:
          command: |
            pip install --upgrade pip
            pip install pylint
            pip install yapf
      - *save_repo

  check_fmt:
    <<: *default_config
    steps:
      - restore
      - run: yapf . --recursive --quiet

  lint:
    <<: *default_config
    steps:
      - restore
      - run: pylint src --fail-under=9

  deploy:
    docker:
      - image: cimg/base:2021.03
    steps:
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts

          ssh $DEPLOY_USER@$DEPLOY_HOST "cd $REMOTE_DIR && git fetch origin && git reset --hard origin/master && pip install -r requirements.txt && supervisorctl restart anathema"

workflows:
  main:
    jobs:
      - install
      - check_fmt:
          requires:
            - install
      - lint:
           requires:
             - install
      - deploy:
          requires:
            - check_fmt
            - lint
          filters:
            branches:
              only: master
